title: Showbizz Plus
url: false
# url: https://showbizz.net/series/
order: 22
description: Avec l'achat de QuiJoueQuie, Happy Geeks Médias à tout en main pour faire jouer la synergie entre ses plateformes. Showbizz+ permettra aux utilisateurs de suivre l'actualité culturelle ainsi que de rester informé sur leurs séries favorites.
tags:
- Vue.js 2
- Nuxt.js 2
- Foundation
- Headless
- Laravel Nova
- Auth
